/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airport;

import java.awt.event.ActionEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.*;


public class App extends javax.swing.JFrame {

    private Vector airport = new Vector();
    private Vector airplane = new Vector();
    private Vector flight = new Vector();


    /**
     * Creates new form App
     */
    public App() {
        Main.loadFromFileAirport(Main.airportST, ".//data//airports.txt");
        Main.loadFromFileAirplane(Main.airportST, Main.airplaneST, ".//data//airplanes.txt");
        Main.loadFromFileFlight(Main.airportST, Main.airplaneST, Main.flightST, ".//data//flights.txt");
        initComponents();


        for (String key : Main.airportST.keys()) {
            airport.addElement(key);
        }

        jComboBoxAirport.setModel(new DefaultComboBoxModel(airport));

        for (String key : Main.airplaneST.keys()) {
            airplane.addElement(key);
        }

        jComboBoxAirplane.setModel(new DefaultComboBoxModel(airplane));


        for (Date key : Main.flightST.keys()) {
            flight.addElement(key);
        }

        jComboBoxFlight.setModel(new DefaultComboBoxModel(flight));


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTabbedPaneMain = new javax.swing.JTabbedPane();
        jPanelAiport = new javax.swing.JPanel();
        jComboBoxAirport = new javax.swing.JComboBox<>();
        jLabelCode = new javax.swing.JLabel();
        jLabelAirportName = new javax.swing.JLabel();
        jLabelCity = new javax.swing.JLabel();
        jLabelCountry = new javax.swing.JLabel();
        jLabelContinent = new javax.swing.JLabel();
        jLabelRating = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldCity = new javax.swing.JTextField();
        jTextFieldCountry = new javax.swing.JTextField();
        jTextFieldContinent = new javax.swing.JTextField();
        jTextFieldRating = new javax.swing.JTextField();
        jTextFieldAirportName = new javax.swing.JTextField();
        jButtonAddAirport = new javax.swing.JButton();
        jButtonRemoveAirport = new javax.swing.JButton();
        jButtonEditAirport = new javax.swing.JButton();
        jButtonListAirport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldXAxis = new javax.swing.JTextField();
        jTextFieldYAxis = new javax.swing.JTextField();
        jPanelAirplane = new javax.swing.JPanel();
        jComboBoxAirplane = new javax.swing.JComboBox<>();
        jLabelId = new javax.swing.JLabel();
        jLabelModel = new javax.swing.JLabel();
        jLabelAirplaneName = new javax.swing.JLabel();
        jLabelAirline = new javax.swing.JLabel();
        jLabelCruiseSpeed = new javax.swing.JLabel();
        jLabelCruiseAltitude = new javax.swing.JLabel();
        jLabelMaxDistance = new javax.swing.JLabel();
        jLabelCurrentAirport = new javax.swing.JLabel();
        jLabelMaxCapacity = new javax.swing.JLabel();
        jLabelFuelCapacity = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldModel = new javax.swing.JTextField();
        jTextFieldAirplaneName = new javax.swing.JTextField();
        jTextFieldAirline = new javax.swing.JTextField();
        jTextFieldCruiseSpeed = new javax.swing.JTextField();
        jTextFieldCruiseAltitude = new javax.swing.JTextField();
        jTextFieldMaxDistance = new javax.swing.JTextField();
        jTextFieldCurrentAirport = new javax.swing.JTextField();
        jTextFieldMaxCapacity = new javax.swing.JTextField();
        jTextFieldFuelCapacity = new javax.swing.JTextField();
        jButtonAddAirplane = new javax.swing.JButton();
        jButtonRemoveAirplane = new javax.swing.JButton();
        jButtonEditAirplane = new javax.swing.JButton();
        jButtonListAirplane = new javax.swing.JButton();
        jPanelFlight = new javax.swing.JPanel();
        jComboBoxFlight = new javax.swing.JComboBox<>();
        jLabelDate = new javax.swing.JLabel();
        jLabelAirplaneID = new javax.swing.JLabel();
        jLabelOrigin = new javax.swing.JLabel();
        jLabelDestination = new javax.swing.JLabel();
        jLabelPassengers = new javax.swing.JLabel();
        jLabelDistance = new javax.swing.JLabel();
        jLabelFlightAltitude = new javax.swing.JLabel();
        jLabelWindVelocity = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jTextFieldAirplaneID = new javax.swing.JTextField();
        jTextFieldOrigin = new javax.swing.JTextField();
        jTextFieldDestination = new javax.swing.JTextField();
        jTextFieldPassengers = new javax.swing.JTextField();
        jTextFieldDistance = new javax.swing.JTextField();
        jTextFieldFlightAltitude = new javax.swing.JTextField();
        jTextFieldWindVelocity = new javax.swing.JTextField();
        jButtonAddFlight = new javax.swing.JButton();
        jButtonRemoveFlight = new javax.swing.JButton();
        jButtonEditFlight = new javax.swing.JButton();
        jButtonListFlight = new javax.swing.JButton();
        jPanelDraw = new javax.swing.JPanel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxAirport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        jComboBoxAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAirportActionPerformed(evt);
            }
        });

        jLabelCode.setText("Code:");

        jLabelAirportName.setText("Name:");

        jLabelCity.setText("City:");

        jLabelCountry.setText("Country:");

        jLabelContinent.setText("Continent:");

        jLabelRating.setText("Rating:");

        jTextFieldCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodeActionPerformed(evt);
            }
        });

        jTextFieldContinent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContinentActionPerformed(evt);
            }
        });

        jButtonAddAirport.setText("Add");
        jButtonAddAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAirportActionPerformed(evt);
            }
        });

        jButtonRemoveAirport.setText("Remove");
        jButtonRemoveAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveAirportActionPerformed(evt);
            }
        });

        jButtonEditAirport.setText("Edit");
        jButtonEditAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditAirportActionPerformed(evt);
            }
        });

        jButtonListAirport.setText("List");

        jLabel1.setText("X Axis");

        jLabel2.setText("Y Axis");

        jTextFieldXAxis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldXAxisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAiportLayout = new javax.swing.GroupLayout(jPanelAiport);
        jPanelAiport.setLayout(jPanelAiportLayout);
        jPanelAiportLayout.setHorizontalGroup(
                jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAiportLayout.createSequentialGroup()
                                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBoxAirport, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelAiportLayout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanelAiportLayout.createSequentialGroup()
                                                                        .addComponent(jButtonAddAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jButtonRemoveAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jButtonEditAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(jPanelAiportLayout.createSequentialGroup()
                                                                        .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabelCode)
                                                                                .addComponent(jLabelAirportName)
                                                                                .addComponent(jLabelCity)
                                                                                .addComponent(jLabelCountry)
                                                                                .addComponent(jLabelContinent)
                                                                                .addComponent(jLabelRating)
                                                                                .addComponent(jLabel1))
                                                                        .addGap(51, 51, 51)
                                                                        .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(jTextFieldRating)
                                                                                .addComponent(jTextFieldContinent, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                                                                .addComponent(jTextFieldCountry)
                                                                                .addComponent(jTextFieldCity)
                                                                                .addComponent(jTextFieldAirportName)
                                                                                .addComponent(jTextFieldCode)
                                                                                .addComponent(jTextFieldXAxis)
                                                                                .addComponent(jTextFieldYAxis)))))
                                                .addGroup(jPanelAiportLayout.createSequentialGroup()
                                                        .addGap(109, 109, 109)
                                                        .addComponent(jButtonListAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanelAiportLayout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(jLabel2))))
                                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanelAiportLayout.setVerticalGroup(
                jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAiportLayout.createSequentialGroup()
                                .addComponent(jComboBoxAirport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelCode)
                                        .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldAirportName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelAirportName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCity))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCountry))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelContinent))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelRating)
                                        .addComponent(jTextFieldRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextFieldXAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jTextFieldYAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonAddAirport)
                                        .addComponent(jButtonRemoveAirport)
                                        .addComponent(jButtonEditAirport))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonListAirport)
                                .addContainerGap(157, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("Airport", jPanelAiport);

        jComboBoxAirplane.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        jComboBoxAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAirplaneActionPerformed(evt);
            }
        });

        jLabelId.setText("Id:");

        jLabelModel.setText("Model:");

        jLabelAirplaneName.setText("Name:");

        jLabelAirline.setText("Airline:");

        jLabelCruiseSpeed.setText("Cruise Speed:");

        jLabelCruiseAltitude.setText("Cruise Altitude:");

        jLabelMaxDistance.setText("Max Distance:");

        jLabelCurrentAirport.setText("Current Airport:");

        jLabelMaxCapacity.setText("Max Capacity:");

        jLabelFuelCapacity.setText("Fuel Capacity:");

        jButtonAddAirplane.setText("Add");
        jButtonAddAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAirplaneActionPerformed(evt);
            }
        });

        jButtonRemoveAirplane.setText("Remove");
        jButtonRemoveAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveAirplaneActionPerformed(evt);
            }
        });

        jButtonEditAirplane.setText("Edit");
        jButtonEditAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditAirplaneActionPerformed(evt);
            }
        });

        jButtonListAirplane.setText("List");

        javax.swing.GroupLayout jPanelAirplaneLayout = new javax.swing.GroupLayout(jPanelAirplane);
        jPanelAirplane.setLayout(jPanelAirplaneLayout);
        jPanelAirplaneLayout.setHorizontalGroup(
                jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAirplaneLayout.createSequentialGroup()
                                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelAirplaneLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonAddAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButtonListAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanelAirplaneLayout.createSequentialGroup()
                                                                .addComponent(jButtonRemoveAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonEditAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jComboBoxAirplane, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAirplaneLayout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabelId)
                                                                .addComponent(jLabelModel)
                                                                .addComponent(jLabelAirplaneName)
                                                                .addComponent(jLabelAirline)
                                                                .addComponent(jLabelCruiseSpeed)
                                                                .addComponent(jLabelCruiseAltitude)
                                                                .addComponent(jLabelMaxDistance)
                                                                .addComponent(jLabelCurrentAirport)
                                                                .addComponent(jLabelMaxCapacity)
                                                                .addComponent(jLabelFuelCapacity))
                                                        .addGap(36, 36, 36)
                                                        .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jTextFieldMaxCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextFieldFuelCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextFieldCurrentAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextFieldMaxDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextFieldCruiseAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextFieldCruiseSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextFieldAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextFieldAirplaneName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanelAirplaneLayout.setVerticalGroup(
                jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAirplaneLayout.createSequentialGroup()
                                .addComponent(jComboBoxAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelId)
                                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelModel))
                                .addGap(6, 6, 6)
                                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldAirplaneName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelAirplaneName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldAirline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelAirline))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldCruiseSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCruiseSpeed))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldCruiseAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCruiseAltitude))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldMaxDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelMaxDistance))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldCurrentAirport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCurrentAirport))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldMaxCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelMaxCapacity))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldFuelCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelFuelCapacity))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonAddAirplane)
                                        .addComponent(jButtonRemoveAirplane)
                                        .addComponent(jButtonEditAirplane))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonListAirplane)
                                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("Airplane", jPanelAirplane);

        jComboBoxFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        jComboBoxFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFlightActionPerformed(evt);
            }
        });

        jLabelDate.setText("Date:");

        jLabelAirplaneID.setText("Airplane ID:");

        jLabelOrigin.setText("Origin:");

        jLabelDestination.setText("Destination:");

        jLabelPassengers.setText("Passengers:");

        jLabelDistance.setText("Distance:");

        jLabelFlightAltitude.setText("Flight Altitude:");

        jLabelWindVelocity.setText("Wind Velocity:");

        jTextFieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateActionPerformed(evt);
            }
        });

        jTextFieldOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOriginActionPerformed(evt);
            }
        });

        jTextFieldFlightAltitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFlightAltitudeActionPerformed(evt);
            }
        });

        jButtonAddFlight.setText("Add");
        jButtonAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddFlightActionPerformed(evt);
            }
        });

        jButtonRemoveFlight.setText("Remove");
        jButtonRemoveFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveFlightActionPerformed(evt);
            }
        });

        jButtonEditFlight.setText("Edit");
        jButtonEditFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditFlightActionPerformed(evt);
            }
        });

        jButtonListFlight.setText("List");

        javax.swing.GroupLayout jPanelFlightLayout = new javax.swing.GroupLayout(jPanelFlight);
        jPanelFlight.setLayout(jPanelFlightLayout);
        jPanelFlightLayout.setHorizontalGroup(
                jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelFlightLayout.createSequentialGroup()
                                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jComboBoxFlight, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanelFlightLayout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabelDate)
                                                                .addComponent(jLabelAirplaneID)
                                                                .addComponent(jLabelOrigin)
                                                                .addComponent(jLabelDestination)
                                                                .addComponent(jLabelPassengers)
                                                                .addComponent(jLabelDistance)
                                                                .addComponent(jLabelFlightAltitude)
                                                                .addComponent(jLabelWindVelocity))
                                                        .addGap(51, 51, 51)
                                                        .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jTextFieldDate, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                                                .addComponent(jTextFieldAirplaneID)
                                                                .addComponent(jTextFieldOrigin)
                                                                .addComponent(jTextFieldDestination)
                                                                .addComponent(jTextFieldPassengers)
                                                                .addComponent(jTextFieldDistance)
                                                                .addComponent(jTextFieldFlightAltitude)
                                                                .addComponent(jTextFieldWindVelocity))))
                                        .addGroup(jPanelFlightLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jButtonAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jButtonListFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButtonRemoveFlight, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonEditFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanelFlightLayout.setVerticalGroup(
                jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelFlightLayout.createSequentialGroup()
                                .addComponent(jComboBoxFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelDate)
                                        .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelAirplaneID)
                                        .addComponent(jTextFieldAirplaneID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelOrigin)
                                        .addComponent(jTextFieldOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelDestination)
                                        .addComponent(jTextFieldDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelPassengers)
                                        .addComponent(jTextFieldPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelDistance)
                                        .addComponent(jTextFieldDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelFlightAltitude)
                                        .addComponent(jTextFieldFlightAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelWindVelocity)
                                        .addComponent(jTextFieldWindVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonAddFlight)
                                        .addComponent(jButtonRemoveFlight)
                                        .addComponent(jButtonEditFlight))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonListFlight)
                                .addGap(0, 110, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("Flight", jPanelFlight);

        javax.swing.GroupLayout jPanelDrawLayout = new javax.swing.GroupLayout(jPanelDraw);
        jPanelDraw.setLayout(jPanelDrawLayout);
        jPanelDrawLayout.setHorizontalGroup(
                jPanelDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 528, Short.MAX_VALUE)
        );
        jPanelDrawLayout.setVerticalGroup(
                jPanelDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 461, Short.MAX_VALUE)
        );

        jTabbedPaneMain.addTab("Draw", jPanelDraw);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPaneMain)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPaneMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodeActionPerformed(ActionEvent evt) {
    }

    private void jTextFieldContinentActionPerformed(ActionEvent evt) {
    }

    private void jComboBoxAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAirplaneActionPerformed
        JComboBox cb = (JComboBox) evt.getSource();
        String key = (String) cb.getSelectedItem();

        jTextFieldCode.setText(Main.airportST.get(key).getCode());
        jTextFieldAirportName.setText(Main.airportST.get(key).getName());
        jTextFieldCity.setText(Main.airportST.get(key).getCity());
        jTextFieldCountry.setText(Main.airportST.get(key).getCountry());
        jTextFieldContinent.setText(Main.airportST.get(key).getContinent());
        jTextFieldRating.setText(Float.toString(Main.airportST.get(key).getRating()));
        jTextFieldXAxis.setText(Double.toString(Main.airportST.get(key).getxAxis()));
        jTextFieldYAxis.setText(Double.toString(Main.airportST.get(key).getyAxis()));
    }//GEN-LAST:event_jComboBoxAirplaneActionPerformed

    private void jComboBoxAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAirportActionPerformed
        JComboBox cb = (JComboBox) evt.getSource();
        String key = (String) cb.getSelectedItem();
        jTextFieldId.setText(Main.airplaneST.get(key).getId());
        jTextFieldModel.setText(Main.airplaneST.get(key).getModel());
        jTextFieldAirplaneName.setText(Main.airplaneST.get(key).getName());
        jTextFieldAirline.setText(Main.airplaneST.get(key).getAirline());
        jTextFieldCruiseSpeed.setText(Integer.toString(Main.airplaneST.get(key).getCruiseSpeed()));
        jTextFieldCruiseAltitude.setText(Integer.toString(Main.airplaneST.get(key).getCruiseAltitude()));
        jTextFieldMaxDistance.setText(Integer.toString(Main.airplaneST.get(key).getMaxDistance()));
        jTextFieldCurrentAirport.setText(Main.airplaneST.get(key).getCurrentAirport());
        jTextFieldMaxCapacity.setText(Integer.toString(Main.airplaneST.get(key).getMaxCapacity()));
        jTextFieldFuelCapacity.setText(Integer.toString(Main.airplaneST.get(key).getFuelCapacity()));

    }//GEN-LAST:event_jComboBoxAirportActionPerformed

    private void jComboBoxFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFlightActionPerformed

        JComboBox cb = (JComboBox) evt.getSource();
        DateFormat workPls = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        Date key = (Date) cb.getSelectedItem();

        jTextFieldDate.setText(workPls.format(Main.flightST.get(key).getDate()));
        jTextFieldAirplaneID.setText(Main.flightST.get(key).getAirplaneID());
        jTextFieldOrigin.setText(Main.flightST.get(key).getOrigin());
        jTextFieldDestination.setText(Main.flightST.get(key).getDestination());
        jTextFieldPassengers.setText(Integer.toString(Main.flightST.get(key).getPassengers()));
        jTextFieldDistance.setText(Integer.toString(Main.flightST.get(key).getDistance()));
        jTextFieldFlightAltitude.setText(Integer.toString(Main.flightST.get(key).getFlightAltitude()));
        jTextFieldWindVelocity.setText(Integer.toString(Main.flightST.get(key).getWindVelocity()));

    }//GEN-LAST:event_jComboBoxFlightActionPerformed

    private void jButtonAddAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAirportActionPerformed

        if (!Main.airportST.contains(jTextFieldCode.getText())) {
            Airport newA = new Airport(jTextFieldCode.getText(), jTextFieldAirportName.getText(), jTextFieldCity.getText(),
                    jTextFieldCountry.getText(), jTextFieldContinent.getText(), Float.parseFloat(jTextFieldYAxis.getText()),
                    Double.parseDouble(jTextFieldXAxis.getText()), Double.parseDouble(jTextFieldRating.getText()));

            Main.airportST.put(jTextFieldCode.getText(), newA);

            if (Main.airportST.contains(jTextFieldCode.getText())) {
                JOptionPane.showMessageDialog(null, "Airport: " + jTextFieldCode.getText() + " inserted!", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
                airport.addElement(jTextFieldCode.getText());
                jComboBoxAirport.setSelectedItem(airport.get(airport.size() - 1));
            } else {
                JOptionPane.showMessageDialog(null, "Unknown error!", "Warning :|", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "The following airport already exists: " + jTextFieldCode.getText(), "Error :(", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAddAirportActionPerformed

    private void jButtonRemoveAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveAirportActionPerformed

        String airportCode = jComboBoxAirport.getSelectedItem().toString();

        Main.airportST.delete(airportCode);
        if (!Main.airportST.contains(airportCode)) {
            JOptionPane.showMessageDialog(null, "Airport: " + airportCode + " removed!", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
            airport.remove(airportCode);
        } else {
            JOptionPane.showMessageDialog(null, "Airport: " + airportCode + " was not removed!", "!", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_jButtonRemoveAirportActionPerformed

    private void jButtonEditAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditAirportActionPerformed

        String airportCode = jComboBoxAirport.getSelectedItem().toString();

        Main.airportST.get(airportCode).setName(jTextFieldAirportName.getText());
        Main.airportST.get(airportCode).setCity(jTextFieldCity.toString());
        Main.airportST.get(airportCode).setCountry(jTextFieldCountry.getText());
        Main.airportST.get(airportCode).setContinent(jTextFieldContinent.getText());
        Main.airportST.get(airportCode).setRating(Float.parseFloat(jTextFieldRating.getText()));
        Main.airportST.get(airportCode).setxAxis(Double.parseDouble(jTextFieldXAxis.getText()));
        Main.airportST.get(airportCode).setyAxis(Double.parseDouble(jTextFieldYAxis.getText()));

        if (Main.airportST.get(airportCode).getName().equals(jTextFieldAirportName.getText())
                && Main.airportST.get(airportCode).getCity().equals(jTextFieldCity.toString())
                && Main.airportST.get(airportCode).getCountry().equals(jTextFieldCountry.getText())
                && Main.airportST.get(airportCode).getContinent().equals(jTextFieldContinent.getText())
                && Main.airportST.get(airportCode).getRating().equals(Float.parseFloat(jTextFieldRating.getText()))
                && Main.airportST.get(airportCode).getxAxis() == (Double.parseDouble(jTextFieldXAxis.getText()))
                && Main.airportST.get(airportCode).getyAxis() == (Double.parseDouble(jTextFieldYAxis.getText()))) {
            JOptionPane.showMessageDialog(null, "Airport: " + airportCode + " updated!", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Error while editing!", "Warning :|", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButtonEditAirportActionPerformed

    private void jButtonAddAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAirplaneActionPerformed
        if (!Main.airplaneST.contains(jTextFieldId.getText())) {
            if (Main.airportST.contains(jTextFieldCurrentAirport.getText())) {

                Airplane newA = new Airplane(jTextFieldId.getText(), jTextFieldModel.getText(), jTextFieldAirplaneName.getText(),
                        jTextFieldAirline.getText(), Integer.parseInt(jTextFieldCruiseSpeed.getText()),
                        Integer.parseInt(jTextFieldCruiseAltitude.getText()), Integer.parseInt(jTextFieldMaxDistance.getText()),
                        jTextFieldCurrentAirport.getText(), Integer.parseInt(jTextFieldMaxCapacity.getText()),
                        Integer.parseInt(jTextFieldFuelCapacity.getText()));

                Main.airplaneST.put(jTextFieldId.getText(), newA);

                if (Main.airplaneST.contains(jTextFieldId.getText())) {
                    JOptionPane.showMessageDialog(null, "Airplane: " + jTextFieldId.getText() + " inserted!", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
                    airplane.addElement(jTextFieldId.getText());
                    jComboBoxAirplane.setSelectedItem(airplane.get(airplane.size() - 1));
                } else {
                    JOptionPane.showMessageDialog(null, "Unknown error!", "Warning :|", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "The airport: " + jTextFieldCurrentAirport.getText() + " does not exists!", "Error :(", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "The following airplane already exists: " + jTextFieldId.getText(), "Error :(", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAddAirplaneActionPerformed

    private void jButtonRemoveAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveAirplaneActionPerformed

        String airplaneID = jComboBoxAirplane.getSelectedItem().toString();

        for (String a : Main.airportST.inOrder()) {
            for (Date f : Main.airportST.get(a).getFlightOriST().inOrder()) {
                if (Main.airportST.get(a).getFlightOriST().get(f).getAirplaneID().equals(airplaneID)) {
                    flight.remove(f);
                    Main.airportST.get(a).getFlightOriST().delete(f);
                }
            }
            for (Date f : Main.airportST.get(a).getFlightDestST().inOrder()) {
                if (Main.airportST.get(a).getFlightDestST().get(f).getAirplaneID().equals(airplaneID)) {
                    flight.remove(f);
                    Main.airportST.get(a).getFlightDestST().delete(f);
                }
            }
            Main.airportST.get(a).getAirplaneST().delete(airplaneID);
        }

        Main.airplaneST.delete(airplaneID);
        if (!Main.airplaneST.contains(airplaneID)) {
            JOptionPane.showMessageDialog(null, "Airplane: " + airplaneID + " removed!", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
            airplane.remove(airplaneID);
        } else {
            JOptionPane.showMessageDialog(null, "Airplane: " + airplaneID + " was not removed!", "!", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_jButtonRemoveAirplaneActionPerformed

    private void jButtonEditAirplaneActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonEditAirplaneActionPerformed

        String airplaneID = jComboBoxAirplane.getSelectedItem().toString();

        Main.airplaneST.get(airplaneID).setModel(jTextFieldModel.getText());
        Main.airplaneST.get(airplaneID).setName(jTextFieldAirplaneName.getText());
        Main.airplaneST.get(airplaneID).setAirline(jTextFieldAirline.getText());
        Main.airplaneST.get(airplaneID).setCruiseSpeed(Integer.parseInt(jTextFieldCruiseSpeed.toString()));
        Main.airplaneST.get(airplaneID).setCruiseAltitude(Integer.parseInt(jTextFieldCruiseAltitude.getText()));
        Main.airplaneST.get(airplaneID).setMaxDistance(Integer.parseInt(jTextFieldMaxDistance.getText()));
        Main.airplaneST.get(airplaneID).setCurrentAirport(jTextFieldCurrentAirport.getText());
        Main.airplaneST.get(airplaneID).setFuelCapacity(Integer.parseInt(jTextFieldMaxCapacity.getText()));
        Main.airplaneST.get(airplaneID).setMaxCapacity(Integer.parseInt(jTextFieldFuelCapacity.getText()));

        if (Main.airplaneST.get(airplaneID).getModel().equals(jTextFieldModel.getText())
                && Main.airplaneST.get(airplaneID).getName().equals(jTextFieldAirplaneName.getText())
                && Main.airplaneST.get(airplaneID).getAirline().equals(jTextFieldAirline.getText())
                && Main.airplaneST.get(airplaneID).getCruiseSpeed().equals(Integer.parseInt(jTextFieldCruiseSpeed.toString()))
                && Main.airplaneST.get(airplaneID).getCruiseAltitude().equals(Integer.parseInt(jTextFieldCruiseAltitude.getText()))
                && Main.airplaneST.get(airplaneID).getMaxDistance().equals(Integer.parseInt(jTextFieldMaxDistance.getText()))
                && Main.airplaneST.get(airplaneID).getCurrentAirport().equals(jTextFieldCurrentAirport.getText())
                && Main.airplaneST.get(airplaneID).getMaxCapacity().equals(Integer.parseInt(jTextFieldMaxCapacity.getText()))
                && Main.airplaneST.get(airplaneID).getFuelCapacity().equals(Integer.parseInt(jTextFieldFuelCapacity.getText()))) {
            JOptionPane.showMessageDialog(null, "Airplane: " + airplaneID + " updated!", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Error while editing!", "Warning :|", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jButtonEditAirplaneActionPerformed

    private void jButtonAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddFlightActionPerformed

    private void jButtonRemoveFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoveFlightActionPerformed

    private void jButtonEditFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditFlightActionPerformed

    private void jTextFieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateActionPerformed

    private void jTextFieldOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOriginActionPerformed
        // TODO add your ndling code here:ha
    }//GEN-LAST:event_jTextFieldOriginActionPerformed

    private void jTextFieldFlightAltitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFlightAltitudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFlightAltitudeActionPerformed

    private void jTextFieldXAxisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldXAxisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldXAxisActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddAirplane;
    private javax.swing.JButton jButtonAddAirport;
    private javax.swing.JButton jButtonAddFlight;
    private javax.swing.JButton jButtonEditAirplane;
    private javax.swing.JButton jButtonEditAirport;
    private javax.swing.JButton jButtonEditFlight;
    private javax.swing.JButton jButtonListAirplane;
    private javax.swing.JButton jButtonListAirport;
    private javax.swing.JButton jButtonListFlight;
    private javax.swing.JButton jButtonRemoveAirplane;
    private javax.swing.JButton jButtonRemoveAirport;
    private javax.swing.JButton jButtonRemoveFlight;
    private javax.swing.JComboBox<String> jComboBoxAirplane;
    private javax.swing.JComboBox<String> jComboBoxAirport;
    private javax.swing.JComboBox<String> jComboBoxFlight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAirline;
    private javax.swing.JLabel jLabelAirplaneID;
    private javax.swing.JLabel jLabelAirplaneName;
    private javax.swing.JLabel jLabelAirportName;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelContinent;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelCruiseAltitude;
    private javax.swing.JLabel jLabelCruiseSpeed;
    private javax.swing.JLabel jLabelCurrentAirport;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDestination;
    private javax.swing.JLabel jLabelDistance;
    private javax.swing.JLabel jLabelFlightAltitude;
    private javax.swing.JLabel jLabelFuelCapacity;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMaxCapacity;
    private javax.swing.JLabel jLabelMaxDistance;
    private javax.swing.JLabel jLabelModel;
    private javax.swing.JLabel jLabelOrigin;
    private javax.swing.JLabel jLabelPassengers;
    private javax.swing.JLabel jLabelRating;
    private javax.swing.JLabel jLabelWindVelocity;
    private javax.swing.JPanel jPanelAiport;
    private javax.swing.JPanel jPanelAirplane;
    private javax.swing.JPanel jPanelDraw;
    private javax.swing.JPanel jPanelFlight;
    private javax.swing.JTabbedPane jTabbedPaneMain;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldAirline;
    private javax.swing.JTextField jTextFieldAirplaneID;
    private javax.swing.JTextField jTextFieldAirplaneName;
    private javax.swing.JTextField jTextFieldAirportName;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldContinent;
    private javax.swing.JTextField jTextFieldCountry;
    private javax.swing.JTextField jTextFieldCruiseAltitude;
    private javax.swing.JTextField jTextFieldCruiseSpeed;
    private javax.swing.JTextField jTextFieldCurrentAirport;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldDestination;
    private javax.swing.JTextField jTextFieldDistance;
    private javax.swing.JTextField jTextFieldFlightAltitude;
    private javax.swing.JTextField jTextFieldFuelCapacity;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldMaxCapacity;
    private javax.swing.JTextField jTextFieldMaxDistance;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldOrigin;
    private javax.swing.JTextField jTextFieldPassengers;
    private javax.swing.JTextField jTextFieldRating;
    private javax.swing.JTextField jTextFieldWindVelocity;
    private javax.swing.JTextField jTextFieldXAxis;
    private javax.swing.JTextField jTextFieldYAxis;
    // End of variables declaration//GEN-END:variables
}
