/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airport;

import java.awt.event.ActionEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.Vector;
import javax.swing.*;


public class App extends javax.swing.JFrame {

    private Vector airport = new Vector();
    private Vector airplane = new Vector();
    private Vector flight = new Vector();
    private Vector airplanePicker = new Vector();
    private DesignMap map;


    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        Main.loadFromFileAirport(Main.airportST, ".//data//airports.txt");
        Main.loadFromFileAirplane(Main.airportST, Main.airplaneST, ".//data//airplanes.txt");
        Main.loadFromFileFlight(Main.airportST, Main.airplaneST, Main.flightST, ".//data//flights.txt");


        for (String key : Main.airportST.keys()) {
            airport.addElement(key);
        }

        for (String key : Main.airplaneST.keys()) {
            airplane.addElement(key);
        }

        for (Date key : Main.flightST.keys()) {
            flight.addElement(key);
        }

        jComboBoxAirport.setModel(new DefaultComboBoxModel(airport));
        jComboBoxAirportConnection1.setModel(new DefaultComboBoxModel(airport));
        jComboBoxAirportConnection2.setModel(new DefaultComboBoxModel(airport));
        jComboBoxAirplane.setModel(new DefaultComboBoxModel(airplane));
        jComboBoxFlight.setModel(new DefaultComboBoxModel(flight));


        int mapHeight = jInternalFrameMap.getHeight() - 50;
        int mapWidth = jInternalFrameMap.getWidth();
        map = new DesignMap(mapWidth, mapHeight);
        jInternalFrameMap.setDefaultCloseOperation(jInternalFrameMap.EXIT_ON_CLOSE);
        jInternalFrameMap.setContentPane(map.view);
        jInternalFrameMap.setVisible(true);
        jInternalFrameMap.setTitle("");


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMain = new javax.swing.JTabbedPane();
        jPanelAiport = new javax.swing.JPanel();
        jComboBoxAirport = new javax.swing.JComboBox<>();
        jLabelCode = new javax.swing.JLabel();
        jLabelAirportName = new javax.swing.JLabel();
        jLabelCity = new javax.swing.JLabel();
        jLabelCountry = new javax.swing.JLabel();
        jLabelContinent = new javax.swing.JLabel();
        jLabelRating = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldCity = new javax.swing.JTextField();
        jTextFieldCountry = new javax.swing.JTextField();
        jTextFieldContinent = new javax.swing.JTextField();
        jTextFieldRating = new javax.swing.JTextField();
        jTextFieldAirportName = new javax.swing.JTextField();
        jButtonAddAirport = new javax.swing.JButton();
        jButtonRemoveAirport = new javax.swing.JButton();
        jButtonEditAirport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldXAxis = new javax.swing.JTextField();
        jTextFieldYAxis = new javax.swing.JTextField();
        jPanelAirplane = new javax.swing.JPanel();
        jComboBoxAirplane = new javax.swing.JComboBox<>();
        jLabelId = new javax.swing.JLabel();
        jLabelModel = new javax.swing.JLabel();
        jLabelAirplaneName = new javax.swing.JLabel();
        jLabelAirline = new javax.swing.JLabel();
        jLabelCruiseSpeed = new javax.swing.JLabel();
        jLabelCruiseAltitude = new javax.swing.JLabel();
        jLabelMaxDistance = new javax.swing.JLabel();
        jLabelCurrentAirport = new javax.swing.JLabel();
        jLabelMaxCapacity = new javax.swing.JLabel();
        jLabelFuelCapacity = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldModel = new javax.swing.JTextField();
        jTextFieldAirplaneName = new javax.swing.JTextField();
        jTextFieldAirline = new javax.swing.JTextField();
        jTextFieldCruiseSpeed = new javax.swing.JTextField();
        jTextFieldCruiseAltitude = new javax.swing.JTextField();
        jTextFieldMaxDistance = new javax.swing.JTextField();
        jTextFieldCurrentAirport = new javax.swing.JTextField();
        jTextFieldMaxCapacity = new javax.swing.JTextField();
        jTextFieldFuelCapacity = new javax.swing.JTextField();
        jButtonAddAirplane = new javax.swing.JButton();
        jButtonRemoveAirplane = new javax.swing.JButton();
        jButtonEditAirplane = new javax.swing.JButton();
        jPanelFlight = new javax.swing.JPanel();
        jComboBoxFlight = new javax.swing.JComboBox<>();
        jLabelDate = new javax.swing.JLabel();
        jLabelAirplaneID = new javax.swing.JLabel();
        jLabelOrigin = new javax.swing.JLabel();
        jLabelDestination = new javax.swing.JLabel();
        jLabelPassengers = new javax.swing.JLabel();
        jLabelDistance = new javax.swing.JLabel();
        jLabelFlightAltitude = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jTextFieldAirplaneID = new javax.swing.JTextField();
        jTextFieldOrigin = new javax.swing.JTextField();
        jTextFieldDestination = new javax.swing.JTextField();
        jTextFieldPassengers = new javax.swing.JTextField();
        jTextFieldDistance = new javax.swing.JTextField();
        jTextFieldFlightAltitude = new javax.swing.JTextField();
        jButtonAddFlight = new javax.swing.JButton();
        jButtonRemoveFlight = new javax.swing.JButton();
        jButtonEditFlight = new javax.swing.JButton();
        jPanelConnections = new javax.swing.JPanel();
        jComboBoxAirportConnection1 = new javax.swing.JComboBox<>();
        jComboBoxAirportConnection2 = new javax.swing.JComboBox<>();
        jButtonAddConnection = new javax.swing.JButton();
        jButtonEP = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxAirplanePicker = new javax.swing.JComboBox<>();
        jButtonFP = new javax.swing.JButton();
        jButtonSP = new javax.swing.JButton();
        jButtonIsConnected = new javax.swing.JButton();
        jButtonFPmost = new javax.swing.JButton();
        jButtonEPmost = new javax.swing.JButton();
        jButtonDP = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonListAll = new javax.swing.JButton();
        jInternalFrameMap = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxAirport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAirportActionPerformed(evt);
            }
        });

        jLabelCode.setText("Code:");

        jLabelAirportName.setText("Name:");

        jLabelCity.setText("City:");

        jLabelCountry.setText("Country:");

        jLabelContinent.setText("Continent:");

        jLabelRating.setText("Rating:");

        jButtonAddAirport.setText("Add");
        jButtonAddAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAirportActionPerformed(evt);
            }
        });

        jButtonRemoveAirport.setText("Remove");
        jButtonRemoveAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveAirportActionPerformed(evt);
            }
        });

        jButtonEditAirport.setText("Edit");
        jButtonEditAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditAirportActionPerformed(evt);
            }
        });

        jLabel1.setText("X Axis");

        jLabel2.setText("Y Axis");

        javax.swing.GroupLayout jPanelAiportLayout = new javax.swing.GroupLayout(jPanelAiport);
        jPanelAiport.setLayout(jPanelAiportLayout);
        jPanelAiportLayout.setHorizontalGroup(
            jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAiportLayout.createSequentialGroup()
                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBoxAirport, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelAiportLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAiportLayout.createSequentialGroup()
                                .addComponent(jButtonAddAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRemoveAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEditAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAiportLayout.createSequentialGroup()
                                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCode)
                                    .addComponent(jLabelAirportName)
                                    .addComponent(jLabelCity)
                                    .addComponent(jLabelCountry)
                                    .addComponent(jLabelContinent)
                                    .addComponent(jLabelRating)
                                    .addComponent(jLabel1))
                                .addGap(51, 51, 51)
                                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldRating)
                                    .addComponent(jTextFieldContinent, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCountry)
                                    .addComponent(jTextFieldCity)
                                    .addComponent(jTextFieldAirportName)
                                    .addComponent(jTextFieldCode)
                                    .addComponent(jTextFieldXAxis)
                                    .addComponent(jTextFieldYAxis)))
                            .addComponent(jLabel2))))
                .addContainerGap(543, Short.MAX_VALUE))
        );
        jPanelAiportLayout.setVerticalGroup(
            jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAiportLayout.createSequentialGroup()
                .addComponent(jComboBoxAirport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCode)
                    .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAirportName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAirportName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCountry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContinent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRating)
                    .addComponent(jTextFieldRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldXAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldYAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelAiportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddAirport)
                    .addComponent(jButtonRemoveAirport)
                    .addComponent(jButtonEditAirport))
                .addContainerGap(275, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("Airport", jPanelAiport);

        jComboBoxAirplane.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAirplaneActionPerformed(evt);
            }
        });

        jLabelId.setText("Id:");

        jLabelModel.setText("Model:");

        jLabelAirplaneName.setText("Name:");

        jLabelAirline.setText("Airline:");

        jLabelCruiseSpeed.setText("Cruise Speed:");

        jLabelCruiseAltitude.setText("Cruise Altitude:");

        jLabelMaxDistance.setText("Max Distance:");

        jLabelCurrentAirport.setText("Current Airport:");

        jLabelMaxCapacity.setText("Max Capacity:");

        jLabelFuelCapacity.setText("Fuel Capacity:");

        jButtonAddAirplane.setText("Add");
        jButtonAddAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAirplaneActionPerformed(evt);
            }
        });

        jButtonRemoveAirplane.setText("Remove");
        jButtonRemoveAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveAirplaneActionPerformed(evt);
            }
        });

        jButtonEditAirplane.setText("Edit");
        jButtonEditAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditAirplaneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAirplaneLayout = new javax.swing.GroupLayout(jPanelAirplane);
        jPanelAirplane.setLayout(jPanelAirplaneLayout);
        jPanelAirplaneLayout.setHorizontalGroup(
            jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAirplaneLayout.createSequentialGroup()
                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAirplaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAddAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemoveAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxAirplane, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAirplaneLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelId)
                                .addComponent(jLabelModel)
                                .addComponent(jLabelAirplaneName)
                                .addComponent(jLabelAirline)
                                .addComponent(jLabelCruiseSpeed)
                                .addComponent(jLabelCruiseAltitude)
                                .addComponent(jLabelMaxDistance)
                                .addComponent(jLabelCurrentAirport)
                                .addComponent(jLabelMaxCapacity)
                                .addComponent(jLabelFuelCapacity))
                            .addGap(36, 36, 36)
                            .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldMaxCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldFuelCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCurrentAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldMaxDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCruiseAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCruiseSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldAirplaneName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(533, Short.MAX_VALUE))
        );
        jPanelAirplaneLayout.setVerticalGroup(
            jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAirplaneLayout.createSequentialGroup()
                .addComponent(jComboBoxAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModel))
                .addGap(6, 6, 6)
                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAirplaneName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAirplaneName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAirline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAirline))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCruiseSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCruiseSpeed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCruiseAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCruiseAltitude))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMaxDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMaxDistance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCurrentAirport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCurrentAirport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMaxCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMaxCapacity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFuelCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFuelCapacity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAirplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddAirplane)
                    .addComponent(jButtonRemoveAirplane)
                    .addComponent(jButtonEditAirplane))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("Airplane", jPanelAirplane);

        jComboBoxFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFlightActionPerformed(evt);
            }
        });

        jLabelDate.setText("Date:");

        jLabelAirplaneID.setText("Airplane ID:");

        jLabelOrigin.setText("Origin:");

        jLabelDestination.setText("Destination:");

        jLabelPassengers.setText("Passengers:");

        jLabelDistance.setText("Distance:");

        jLabelFlightAltitude.setText("Flight Altitude:");

        jButtonAddFlight.setText("Add");
        jButtonAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddFlightActionPerformed(evt);
            }
        });

        jButtonRemoveFlight.setText("Remove");
        jButtonRemoveFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveFlightActionPerformed(evt);
            }
        });

        jButtonEditFlight.setText("Edit");
        jButtonEditFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFlightLayout = new javax.swing.GroupLayout(jPanelFlight);
        jPanelFlight.setLayout(jPanelFlightLayout);
        jPanelFlightLayout.setHorizontalGroup(
            jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFlightLayout.createSequentialGroup()
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxFlight, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFlightLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelDate)
                                .addComponent(jLabelAirplaneID)
                                .addComponent(jLabelOrigin)
                                .addComponent(jLabelDestination)
                                .addComponent(jLabelPassengers)
                                .addComponent(jLabelDistance)
                                .addComponent(jLabelFlightAltitude))
                            .addGap(53, 53, 53)
                            .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldDate, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(jTextFieldAirplaneID)
                                .addComponent(jTextFieldOrigin)
                                .addComponent(jTextFieldDestination)
                                .addComponent(jTextFieldPassengers)
                                .addComponent(jTextFieldDistance)
                                .addComponent(jTextFieldFlightAltitude))))
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemoveFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(550, Short.MAX_VALUE))
        );
        jPanelFlightLayout.setVerticalGroup(
            jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFlightLayout.createSequentialGroup()
                .addComponent(jComboBoxFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDate)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAirplaneID)
                    .addComponent(jTextFieldAirplaneID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrigin)
                    .addComponent(jTextFieldOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDestination)
                    .addComponent(jTextFieldDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassengers)
                    .addComponent(jTextFieldPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDistance)
                    .addComponent(jTextFieldDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFlightAltitude)
                    .addComponent(jTextFieldFlightAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddFlight)
                    .addComponent(jButtonRemoveFlight)
                    .addComponent(jButtonEditFlight))
                .addGap(0, 233, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("Flight", jPanelFlight);

        jComboBoxAirportConnection1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAirportConnection1ActionPerformed(evt);
            }
        });

        jButtonAddConnection.setText("Add Connection");
        jButtonAddConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddConnectionActionPerformed(evt);
            }
        });

        jButtonEP.setText("Economic Path");
        jButtonEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEPActionPerformed(evt);
            }
        });

        jLabel15.setText("Airport 1");

        jLabel17.setText("Airport 2");

        jLabel18.setText("Airplane");

        jButtonFP.setText("Fastest Path");
        jButtonFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFPActionPerformed(evt);
            }
        });

        jButtonSP.setText("Shortest Path");
        jButtonSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSPActionPerformed(evt);
            }
        });

        jButtonIsConnected.setText("Is connected");
        jButtonIsConnected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIsConnectedActionPerformed(evt);
            }
        });

        jButtonFPmost.setText("Fastest Path (optimized by airplane)");
        jButtonFPmost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFPmostActionPerformed(evt);
            }
        });

        jButtonEPmost.setText("Economic Path (optimized by airplane)");
        jButtonEPmost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEPmostActionPerformed(evt);
            }
        });

        jButtonDP.setText("Direct Path");
        jButtonDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConnectionsLayout = new javax.swing.GroupLayout(jPanelConnections);
        jPanelConnections.setLayout(jPanelConnectionsLayout);
        jPanelConnectionsLayout.setHorizontalGroup(
            jPanelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConnectionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConnectionsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAddConnection, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jButtonIsConnected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelConnectionsLayout.createSequentialGroup()
                        .addGroup(jPanelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonDP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelConnectionsLayout.createSequentialGroup()
                                .addGroup(jPanelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxAirportConnection1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jComboBoxAirportConnection2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConnectionsLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jComboBoxAirplanePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 461, Short.MAX_VALUE))
                            .addGroup(jPanelConnectionsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonFPmost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelConnectionsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEPmost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelConnectionsLayout.setVerticalGroup(
            jPanelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConnectionsLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(3, 3, 3)
                .addGroup(jPanelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAirportConnection1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAirportConnection2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAirplanePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConnectionsLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButtonFPmost))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConnectionsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFP)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEP)
                    .addComponent(jButtonEPmost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(jButtonIsConnected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddConnection)
                .addContainerGap())
        );

        jTabbedPaneMain.addTab("Connections", jPanelConnections);

        jButtonListAll.setText("List All");
        jButtonListAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListAllActionPerformed(evt);
            }
        });

        jInternalFrameMap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jInternalFrameMap.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameMap.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jInternalFrameMap.setVisible(true);

        javax.swing.GroupLayout jInternalFrameMapLayout = new javax.swing.GroupLayout(jInternalFrameMap.getContentPane());
        jInternalFrameMap.getContentPane().setLayout(jInternalFrameMapLayout);
        jInternalFrameMapLayout.setHorizontalGroup(
            jInternalFrameMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        jInternalFrameMapLayout.setVerticalGroup(
            jInternalFrameMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonListAll)
                .addContainerGap(792, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jInternalFrameMap)
                    .addGap(48, 48, 48)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonListAll)
                .addContainerGap(515, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jInternalFrameMap)
                    .addGap(58, 58, 58)))
        );

        jTabbedPaneMain.addTab("Draw", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jComboBoxAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAirplaneActionPerformed
        JComboBox cb = (JComboBox) evt.getSource();
        String key = (String) cb.getSelectedItem();

        jTextFieldCode.setText(Main.airportST.get(key).getCode());
        jTextFieldAirportName.setText(Main.airportST.get(key).getName());
        jTextFieldCity.setText(Main.airportST.get(key).getCity());
        jTextFieldCountry.setText(Main.airportST.get(key).getCountry());
        jTextFieldContinent.setText(Main.airportST.get(key).getContinent());
        jTextFieldRating.setText(Float.toString(Main.airportST.get(key).getRating()));
        jTextFieldXAxis.setText(Double.toString(Main.airportST.get(key).getxAxis()));
        jTextFieldYAxis.setText(Double.toString(Main.airportST.get(key).getyAxis()));
    }//GEN-LAST:event_jComboBoxAirplaneActionPerformed

    private void jComboBoxAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAirportActionPerformed
        JComboBox cb = (JComboBox) evt.getSource();
        String key = (String) cb.getSelectedItem();

        jTextFieldId.setText(Main.airplaneST.get(key).getId());
        jTextFieldModel.setText(Main.airplaneST.get(key).getModel());
        jTextFieldAirplaneName.setText(Main.airplaneST.get(key).getName());
        jTextFieldAirline.setText(Main.airplaneST.get(key).getAirline());
        jTextFieldCruiseSpeed.setText(Integer.toString(Main.airplaneST.get(key).getCruiseSpeed()));
        jTextFieldCruiseAltitude.setText(Integer.toString(Main.airplaneST.get(key).getCruiseAltitude()));
        jTextFieldMaxDistance.setText(Integer.toString(Main.airplaneST.get(key).getMaxDistance()));
        jTextFieldCurrentAirport.setText(Main.airplaneST.get(key).getCurrentAirport());
        jTextFieldMaxCapacity.setText(Integer.toString(Main.airplaneST.get(key).getMaxCapacity()));
        jTextFieldFuelCapacity.setText(Integer.toString(Main.airplaneST.get(key).getFuelCapacity()));

    }//GEN-LAST:event_jComboBoxAirportActionPerformed

    private void jComboBoxFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFlightActionPerformed

        JComboBox cb = (JComboBox) evt.getSource();
        DateFormat workPls = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        Date key = (Date) cb.getSelectedItem();

        jTextFieldDate.setText(workPls.format(Main.flightST.get(key).getDate()));
        jTextFieldAirplaneID.setText(Main.flightST.get(key).getAirplaneID());
        jTextFieldOrigin.setText(Main.flightST.get(key).getOrigin());
        jTextFieldDestination.setText(Main.flightST.get(key).getDestination());
        jTextFieldPassengers.setText(Integer.toString(Main.flightST.get(key).getPassengers()));
        jTextFieldDistance.setText(Integer.toString(Main.flightST.get(key).getDistance()));
        jTextFieldFlightAltitude.setText(Integer.toString(Main.flightST.get(key).getFlightAltitude()));

    }//GEN-LAST:event_jComboBoxFlightActionPerformed

    private void jButtonAddAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAirportActionPerformed

        if (!Main.airportST.contains(jTextFieldCode.getText())) {
            Airport newA = new Airport(jTextFieldCode.getText(), jTextFieldAirportName.getText(), jTextFieldCity.getText(),
                    jTextFieldCountry.getText(), jTextFieldContinent.getText(), Float.parseFloat(jTextFieldYAxis.getText()),
                    Double.parseDouble(jTextFieldXAxis.getText()), Double.parseDouble(jTextFieldRating.getText()));

            Main.airportST.put(jTextFieldCode.getText(), newA);

            if (Main.airportST.contains(jTextFieldCode.getText())) {
                JOptionPane.showMessageDialog(null, "Airport: " + jTextFieldCode.getText() + " inserted!", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
                airport.addElement(jTextFieldCode.getText());
                jComboBoxAirport.setSelectedItem(airport.get(airport.size() - 1));
            } else {
                JOptionPane.showMessageDialog(null, "Unknown error!", "Warning :|", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "The following airport already exists: " + jTextFieldCode.getText(), "Error :(", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAddAirportActionPerformed

    private void jButtonRemoveAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveAirportActionPerformed

        String airportCode = jComboBoxAirport.getSelectedItem().toString();

        Main.airportST.delete(airportCode);
        if (!Main.airportST.contains(airportCode)) {
            JOptionPane.showMessageDialog(null, "Airport: " + airportCode + " removed!", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
            airport.remove(airportCode);
        } else {
            JOptionPane.showMessageDialog(null, "Airport: " + airportCode + " was not removed!", "!", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_jButtonRemoveAirportActionPerformed

    private void jButtonEditAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditAirportActionPerformed

        String airportCode = jComboBoxAirport.getSelectedItem().toString();

        Main.airportST.get(airportCode).setName(jTextFieldAirportName.getText());
        Main.airportST.get(airportCode).setCity(jTextFieldCity.getText());
        Main.airportST.get(airportCode).setCountry(jTextFieldCountry.getText());
        Main.airportST.get(airportCode).setContinent(jTextFieldContinent.getText());
        Main.airportST.get(airportCode).setRating(Float.parseFloat(jTextFieldRating.getText()));
        Main.airportST.get(airportCode).setxAxis(Double.parseDouble(jTextFieldXAxis.getText()));
        Main.airportST.get(airportCode).setyAxis(Double.parseDouble(jTextFieldYAxis.getText()));

        if (Main.airportST.get(airportCode).getName().equals(jTextFieldAirportName.getText())
                && Main.airportST.get(airportCode).getCity().equals(jTextFieldCity.getText())
                && Main.airportST.get(airportCode).getCountry().equals(jTextFieldCountry.getText())
                && Main.airportST.get(airportCode).getContinent().equals(jTextFieldContinent.getText())
                && Main.airportST.get(airportCode).getRating().equals(Float.parseFloat(jTextFieldRating.getText()))
                && Main.airportST.get(airportCode).getxAxis() == (Double.parseDouble(jTextFieldXAxis.getText()))
                && Main.airportST.get(airportCode).getyAxis() == (Double.parseDouble(jTextFieldYAxis.getText()))) {
            JOptionPane.showMessageDialog(null, "Airport: " + airportCode + " updated!", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Error while editing!", "Warning :|", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jButtonEditAirportActionPerformed

    private void jButtonAddAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAirplaneActionPerformed
        if (!Main.airplaneST.contains(jTextFieldId.getText())) {
            if (Main.airportST.contains(jTextFieldCurrentAirport.getText())) {

                Airplane newA = new Airplane(jTextFieldId.getText(),
                        jTextFieldModel.getText(), jTextFieldAirplaneName.getText(),
                        jTextFieldAirline.getText(), Integer.parseInt(jTextFieldCruiseSpeed.getText()),
                        Integer.parseInt(jTextFieldCruiseAltitude.getText()), Integer.parseInt(jTextFieldMaxDistance.getText()),
                        jTextFieldCurrentAirport.getText(), Integer.parseInt(jTextFieldMaxCapacity.getText()),
                        Integer.parseInt(jTextFieldFuelCapacity.getText()));

                Main.airplaneST.put(jTextFieldId.getText(), newA);
                Main.airportST.get(jTextFieldCurrentAirport.getText()).getAirplaneST().put(jTextFieldId.getText(), newA);

                if (Main.airplaneST.contains(jTextFieldId.getText())) {
                    JOptionPane.showMessageDialog(null, "Airplane: " + jTextFieldId.getText() + " inserted!", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
                    airplane.addElement(jTextFieldId.getText());
                    jComboBoxAirplane.setSelectedItem(airplane.get(airplane.size() - 1));
                } else {
                    JOptionPane.showMessageDialog(null, "Unknown error!", "Warning :|", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "The airport: " + jTextFieldCurrentAirport.getText() + " does not exists!", "Error :(", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "The following airplane already exists: " + jTextFieldId.getText(), "Error :(", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAddAirplaneActionPerformed

    private void jButtonRemoveAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveAirplaneActionPerformed

        String airplaneID = jComboBoxAirplane.getSelectedItem().toString();

        for (String a : Main.airportST.inOrder()) {
            for (Date f : Main.airportST.get(a).getFlightOriST().inOrder()) {
                if (Main.airportST.get(a).getFlightOriST().get(f).getAirplaneID().equals(airplaneID)) {
                    flight.remove(f);
                    Main.airportST.get(a).getFlightOriST().delete(f);
                }
            }
            for (Date f : Main.airportST.get(a).getFlightDestST().inOrder()) {
                if (Main.airportST.get(a).getFlightDestST().get(f).getAirplaneID().equals(airplaneID)) {
                    flight.remove(f);
                    Main.airportST.get(a).getFlightDestST().delete(f);
                }
            }
            Main.airportST.get(a).getAirplaneST().delete(airplaneID);
        }

        Main.airplaneST.delete(airplaneID);
        if (!Main.airplaneST.contains(airplaneID)) {
            JOptionPane.showMessageDialog(null, "Airplane: " + airplaneID + " removed!", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
            airplane.remove(airplaneID);
        } else {
            JOptionPane.showMessageDialog(null, "Airplane: " + airplaneID + " was not removed!", "!", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_jButtonRemoveAirplaneActionPerformed

    private void jButtonEditAirplaneActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonEditAirplaneActionPerformed

        String airplaneID = jComboBoxAirplane.getSelectedItem().toString();

        if (Main.airportST.contains(jTextFieldCurrentAirport.getText())) {

            Main.airplaneST.get(airplaneID).setModel(jTextFieldModel.getText());
            Main.airplaneST.get(airplaneID).setName(jTextFieldAirplaneName.getText());
            Main.airplaneST.get(airplaneID).setAirline(jTextFieldAirline.getText());
            Main.airplaneST.get(airplaneID).setCruiseSpeed(Integer.parseInt(jTextFieldCruiseSpeed.getText()));
            Main.airplaneST.get(airplaneID).setCruiseAltitude(Integer.parseInt(jTextFieldCruiseAltitude.getText()));
            Main.airplaneST.get(airplaneID).setMaxDistance(Integer.parseInt(jTextFieldMaxDistance.getText()));
            Main.airplaneST.get(airplaneID).setCurrentAirport(jTextFieldCurrentAirport.getText());
            Main.airplaneST.get(airplaneID).setMaxCapacity(Integer.parseInt(jTextFieldMaxCapacity.getText()));
            Main.airplaneST.get(airplaneID).setFuelCapacity(Integer.parseInt(jTextFieldFuelCapacity.getText()));


            if (Main.airplaneST.get(airplaneID).getModel().equals(jTextFieldModel.getText())
                    && Main.airplaneST.get(airplaneID).getName().equals(jTextFieldAirplaneName.getText())
                    && Main.airplaneST.get(airplaneID).getAirline().equals(jTextFieldAirline.getText())
                    && Main.airplaneST.get(airplaneID).getCruiseSpeed().equals(Integer.parseInt(jTextFieldCruiseSpeed.getText()))
                    && Main.airplaneST.get(airplaneID).getCruiseAltitude().equals(Integer.parseInt(jTextFieldCruiseAltitude.getText()))
                    && Main.airplaneST.get(airplaneID).getMaxDistance().equals(Integer.parseInt(jTextFieldMaxDistance.getText()))
                    && Main.airplaneST.get(airplaneID).getCurrentAirport().equals(jTextFieldCurrentAirport.getText())
                    && Main.airplaneST.get(airplaneID).getMaxCapacity().equals(Integer.parseInt(jTextFieldMaxCapacity.getText()))
                    && Main.airplaneST.get(airplaneID).getFuelCapacity().equals(Integer.parseInt(jTextFieldFuelCapacity.getText()))) {

                JOptionPane.showMessageDialog(null, "Airplane: " + airplaneID + " updated!", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Error while editing!", "Warning :|", JOptionPane.WARNING_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Airport " + jTextFieldCurrentAirport.getText()
                    + " does not exists!", "Error :(", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonEditAirplaneActionPerformed

    private void jButtonAddFlightActionPerformed(java.awt.event.ActionEvent evt) throws ParseException {//GEN-FIRST:event_jButtonAddFlightActionPerformed

        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm");

        if (!Main.flightST.contains(dateFormat.parse(jTextFieldDate.getText()))) {
            if (Main.airportST.contains(jTextFieldOrigin.getText()) && Main.airportST.contains(jTextFieldDestination.getText())
                    && Main.airportST.get(jTextFieldOrigin.getText()).getAirplaneST().contains(jTextFieldAirplaneID.getText())) {

                Flight newF = new Flight(dateFormat.parse(jTextFieldDate.getText()),
                        jTextFieldAirplaneID.getText(), jTextFieldOrigin.getText(),
                        jTextFieldDestination.getText(), Integer.parseInt(jTextFieldPassengers.getText()),
                        Integer.parseInt(jTextFieldDistance.getText()), Integer.parseInt(jTextFieldFlightAltitude.getText()));

                Main.airportST.get(jTextFieldOrigin.getText()).getFlightOriST().put(dateFormat.parse(jTextFieldDate.getText()), newF);
                Main.airportST.get(jTextFieldDestination.getText()).getFlightDestST().put(dateFormat.parse(jTextFieldDate.getText()), newF);
                Main.airplaneST.get(jTextFieldAirplaneID.getText()).getFlightsAirplane().put(dateFormat.parse(jTextFieldDate.getText()), newF);
                Main.flightST.put(dateFormat.parse(jTextFieldDate.getText()), newF);

                if (Main.flightST.contains(dateFormat.parse(jTextFieldDate.getText()))) {
                    JOptionPane.showMessageDialog(null, "Flight: " + jTextFieldId.getText() + " inserted!", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
                    flight.addElement(dateFormat.parse(jTextFieldDate.getText()));
                    jComboBoxFlight.setSelectedItem(flight.get(flight.size() - 1));
                } else {
                    JOptionPane.showMessageDialog(null, "Unknown error!", "Warning :|", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "The airport or the airplane does not exists!", "Error :(", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "The following flight already exists: " + jTextFieldDate.getText(), "Error :(", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAddFlightActionPerformed

    private void jButtonRemoveFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveFlightActionPerformed

        Date flightID = (Date) jComboBoxFlight.getSelectedItem();

        for (String a : Main.airportST.inOrder()) {
            if (Main.airportST.get(a).getFlightOriST().contains(flightID)) {
                Main.airportST.get(a).getFlightOriST().delete(flightID);
            } else if (Main.airportST.get(a).getFlightDestST().contains(flightID)) {
                Main.airportST.get(a).getFlightDestST().delete(flightID);
            }
        }
        for (String a : Main.airplaneST.keys()) {
            if (Main.airplaneST.get(a).getFlightsAirplane().contains(flightID)) {
                Main.airplaneST.get(a).getFlightsAirplane().delete(flightID);
            }
        }
        if (Main.flightST.contains(flightID)) {
            Main.flightST.delete(flightID);
        }
        if (!Main.flightST.contains(flightID)) {
            JOptionPane.showMessageDialog(null, "Flight: " + flightID + " removed!", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
            flight.remove(flightID);
        } else {
            JOptionPane.showMessageDialog(null, "Flight: " + flightID + " was not removed!", "!", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButtonRemoveFlightActionPerformed

    private void jButtonEditFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditFlightActionPerformed

        Date flightID = (Date) jComboBoxFlight.getSelectedItem();

        if (Main.airportST.contains(jTextFieldOrigin.getText()) && Main.airportST.contains(jTextFieldDestination.getText())) {
            if (Main.airplaneST.contains(jTextFieldAirplaneID.getText())) {

                Main.flightST.get(flightID).setAirplaneID(jTextFieldAirplaneID.getText());
                Main.flightST.get(flightID).setOrigin(jTextFieldOrigin.getText());
                Main.flightST.get(flightID).setDestination(jTextFieldDestination.getText());
                Main.flightST.get(flightID).setPassengers(Integer.parseInt(jTextFieldPassengers.getText()));
                Main.flightST.get(flightID).setDistance(Integer.parseInt(jTextFieldDistance.getText()));
                Main.flightST.get(flightID).setFlightAltitude(Integer.parseInt(jTextFieldFlightAltitude.getText()));

                if (Main.flightST.get(flightID).getAirplaneID().equals(jTextFieldAirplaneID.getText())
                        && Main.flightST.get(flightID).getOrigin().equals(jTextFieldOrigin.getText())
                        && Main.flightST.get(flightID).getDestination().equals(jTextFieldDestination.getText())
                        && Main.flightST.get(flightID).getPassengers().equals(Integer.parseInt(jTextFieldPassengers.getText()))
                        && Main.flightST.get(flightID).getDistance().equals(Integer.parseInt(jTextFieldDistance.getText()))
                        && Main.flightST.get(flightID).getFlightAltitude().equals(Integer.parseInt(jTextFieldFlightAltitude.getText()))) {

                    JOptionPane.showMessageDialog(null, "Flight: " + flightID + " updated!", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Error while editing!", "Warning :|", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Airplane " + jTextFieldAirplaneID.getText() +
                        " does not exists!", "Error :(", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Airport " + jTextFieldOrigin.getText() + " or "
                    + jTextFieldDestination.getText() + " does not exists!", "Error :(", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEditFlightActionPerformed

    private void jButtonAddConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddConnectionActionPerformed

        Random r = new Random();
        float windVelocity;
        float airTunnel;


        Airport a1 = Main.airportST.get(jComboBoxAirportConnection1.getSelectedItem().toString());
        Airport a2 = Main.airportST.get(jComboBoxAirportConnection2.getSelectedItem().toString());


        double distance = UsefulFunctions.HaversineInKM(a1.getxAxis(), a1.getyAxis(), a2.getxAxis(), a2.getyAxis());

        windVelocity = r.nextInt(11) - r.nextInt(21);
        airTunnel = r.nextInt(40001) - r.nextInt(20001);

        Connection c = new Connection(Main.sd.indexOf(a1.getCode()), Main.sd.indexOf(a2.getCode()), distance, windVelocity, airTunnel);

        Main.sd.digraph().addEdge(c);

        JOptionPane.showMessageDialog(null, "Added a connection between " + a1.getName() + " and " + a2.getName(),
                "Well done :)", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_jButtonAddConnectionActionPerformed

    private void jButtonFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFPActionPerformed

        Airport a1 = Main.airportST.get(jComboBoxAirportConnection1.getSelectedItem().toString());
        Airport a2 = Main.airportST.get(jComboBoxAirportConnection2.getSelectedItem().toString());
        Airplane ap = Main.airplaneST.get(jComboBoxAirplanePicker.getSelectedItem().toString());

        if (a1.equals(a2)) {
            JOptionPane.showMessageDialog(null, "Can't do that with the same airport!" + jTextFieldCode.getText(), "Error :(", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, Main.fastestPath(Main.sd, a1, a2, ap), "Well done :)", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_jButtonFPActionPerformed

    private void jButtonEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEPActionPerformed

        Airport a1 = Main.airportST.get(jComboBoxAirportConnection1.getSelectedItem().toString());
        Airport a2 = Main.airportST.get(jComboBoxAirportConnection2.getSelectedItem().toString());
        Airplane ap = Main.airplaneST.get(jComboBoxAirplanePicker.getSelectedItem().toString());

        if (a1.equals(a2)) {
            JOptionPane.showMessageDialog(null, "Can't do that with the same airport!" + jTextFieldCode.getText(), "Error :(", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, Main.economicPath(Main.sd, a1, a2, ap), "Well done :)", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButtonEPActionPerformed

    private void jButtonSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSPActionPerformed
        Airport a1 = Main.airportST.get(jComboBoxAirportConnection1.getSelectedItem().toString());
        Airport a2 = Main.airportST.get(jComboBoxAirportConnection2.getSelectedItem().toString());

        if (a1.equals(a2)) {
            JOptionPane.showMessageDialog(null, "Can't do that with the same airport!" + jTextFieldCode.getText(), "Error :(", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, Main.shortestPath(Main.sd, a1, a2), "Well done :)", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSPActionPerformed

    private void jButtonIsConnectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIsConnectedActionPerformed

        if (Main.isConnected()) {
            JOptionPane.showMessageDialog(rootPane, "The graph is connected", "Well done :)", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIsConnectedActionPerformed

    private void jButtonFPmostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFPmostActionPerformed
        Airport a1 = Main.airportST.get(jComboBoxAirportConnection1.getSelectedItem().toString());
        Airport a2 = Main.airportST.get(jComboBoxAirportConnection2.getSelectedItem().toString());

        if (a1.equals(a2)) {
            JOptionPane.showMessageDialog(null, "Can't do that with the same airport!" + jTextFieldCode.getText(), "Error :(", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, Main.fastAndFurious(Main.sd, a1, a2), "Well done :)", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jButtonFPmostActionPerformed

    private void jButtonEPmostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEPmostActionPerformed
        Airport a1 = Main.airportST.get(jComboBoxAirportConnection1.getSelectedItem().toString());
        Airport a2 = Main.airportST.get(jComboBoxAirportConnection2.getSelectedItem().toString());

        if (a1.equals(a2)) {
            JOptionPane.showMessageDialog(null, "Can't do that with the same airport!" + jTextFieldCode.getText(), "Error :(", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, Main.mostEconomicPath(Main.sd, a1, a2), "Well done :)", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEPmostActionPerformed

    private void jButtonDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDPActionPerformed

        Airport a1 = Main.airportST.get(jComboBoxAirportConnection1.getSelectedItem().toString());
        Airport a2 = Main.airportST.get(jComboBoxAirportConnection2.getSelectedItem().toString());

        if (a1.equals(a2)) {
            JOptionPane.showMessageDialog(null, "Can't do that with the same airport!" + jTextFieldCode.getText(), "Error :(", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, Main.directPath(Main.sdNoWeight, a1, a2), "Well done :)", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButtonDPActionPerformed

    private void jComboBoxAirportConnection1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAirportConnection1ActionPerformed

        JComboBox cb = (JComboBox) evt.getSource();
        String a = (String) cb.getSelectedItem();

        airplanePicker.clear();

        for (String key : Main.airportST.get(a).getAirplaneST().keys()) {
            airplanePicker.add(key);
        }

        jComboBoxAirplanePicker.setModel(new DefaultComboBoxModel(airplanePicker));
    }//GEN-LAST:event_jComboBoxAirportConnection1ActionPerformed

    private void jButtonListAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListAllActionPerformed
        map.resetMap();
        jInternalFrameMap.setContentPane(map.view);
        for (String i : Main.airportST.inOrder()) {
            map.addNewAirport(Main.airportST.get(i).getyAxis(), Main.airportST.get(i).getxAxis(), Main.airportST.get(i).getCode());
        }
    }//GEN-LAST:event_jButtonListAllActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddAirplane;
    private javax.swing.JButton jButtonAddAirport;
    private javax.swing.JButton jButtonAddConnection;
    private javax.swing.JButton jButtonAddFlight;
    private javax.swing.JButton jButtonDP;
    private javax.swing.JButton jButtonEP;
    private javax.swing.JButton jButtonEPmost;
    private javax.swing.JButton jButtonEditAirplane;
    private javax.swing.JButton jButtonEditAirport;
    private javax.swing.JButton jButtonEditFlight;
    private javax.swing.JButton jButtonFP;
    private javax.swing.JButton jButtonFPmost;
    private javax.swing.JButton jButtonIsConnected;
    private javax.swing.JButton jButtonListAll;
    private javax.swing.JButton jButtonRemoveAirplane;
    private javax.swing.JButton jButtonRemoveAirport;
    private javax.swing.JButton jButtonRemoveFlight;
    private javax.swing.JButton jButtonSP;
    private javax.swing.JComboBox<String> jComboBoxAirplane;
    private javax.swing.JComboBox<String> jComboBoxAirplanePicker;
    private javax.swing.JComboBox<String> jComboBoxAirport;
    private javax.swing.JComboBox<String> jComboBoxAirportConnection1;
    private javax.swing.JComboBox<String> jComboBoxAirportConnection2;
    private javax.swing.JComboBox<String> jComboBoxFlight;
    private javax.swing.JInternalFrame jInternalFrameMap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAirline;
    private javax.swing.JLabel jLabelAirplaneID;
    private javax.swing.JLabel jLabelAirplaneName;
    private javax.swing.JLabel jLabelAirportName;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelContinent;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelCruiseAltitude;
    private javax.swing.JLabel jLabelCruiseSpeed;
    private javax.swing.JLabel jLabelCurrentAirport;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDestination;
    private javax.swing.JLabel jLabelDistance;
    private javax.swing.JLabel jLabelFlightAltitude;
    private javax.swing.JLabel jLabelFuelCapacity;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMaxCapacity;
    private javax.swing.JLabel jLabelMaxDistance;
    private javax.swing.JLabel jLabelModel;
    private javax.swing.JLabel jLabelOrigin;
    private javax.swing.JLabel jLabelPassengers;
    private javax.swing.JLabel jLabelRating;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAiport;
    private javax.swing.JPanel jPanelAirplane;
    private javax.swing.JPanel jPanelConnections;
    private javax.swing.JPanel jPanelFlight;
    private javax.swing.JTabbedPane jTabbedPaneMain;
    private javax.swing.JTextField jTextFieldAirline;
    private javax.swing.JTextField jTextFieldAirplaneID;
    private javax.swing.JTextField jTextFieldAirplaneName;
    private javax.swing.JTextField jTextFieldAirportName;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldContinent;
    private javax.swing.JTextField jTextFieldCountry;
    private javax.swing.JTextField jTextFieldCruiseAltitude;
    private javax.swing.JTextField jTextFieldCruiseSpeed;
    private javax.swing.JTextField jTextFieldCurrentAirport;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldDestination;
    private javax.swing.JTextField jTextFieldDistance;
    private javax.swing.JTextField jTextFieldFlightAltitude;
    private javax.swing.JTextField jTextFieldFuelCapacity;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldMaxCapacity;
    private javax.swing.JTextField jTextFieldMaxDistance;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldOrigin;
    private javax.swing.JTextField jTextFieldPassengers;
    private javax.swing.JTextField jTextFieldRating;
    private javax.swing.JTextField jTextFieldXAxis;
    private javax.swing.JTextField jTextFieldYAxis;
    // End of variables declaration//GEN-END:variables
}
